- name: Checking existing - {{dir}}/{{component}}
  ansible.builtin.shell: java -jar /opt/jenkins-cli.jar -auth admin:{{jenkins_password}} -s http://172.31.7.96:8080 -webSocket get-job {{dir}}/{{component}}
  register: out
  ignore_errors: yes



- name: Create Config file
  ansible.builtin.template:
    src: m-job.xml
    dest: /tmp/m-job.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)
  when: out.rc == 3


- name: Create - "{{dir}}/{{component}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', 'tmp/m-job.xml') }}"
    name: "{{dir}}/{{component}}"
    url: http://172.31.7.96:8080
    user: admin
    password: "{{jenkins_password}}"
  when: out.rc == 3
