
- name: Create Config file
  ansible.builtin.template:
    src: m-job.xml
    dest: /tmp/job.xml

- name: Create - "{{dir}}/{{component}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/m-job.xml') }}"
    name: "{{dir}}/{{component}}"
    url: http://172.31.7.96:8080
    user: admin
    password: "{{jenkins_password}}"