- name: Create - "{{item.dir}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.7.96:8080
    user: admin
    password: "{{jenkins_password}}"
  loop:
    - CIpipeline


- name: create pipe line job
  ansible.builtin.include_tasks:
    file: pipeline.yml
  loop:
    - {name: "frontend" , dir: "CIpipeline"}
    - {name: "cart" , dir: "CIpipeline"}
    - {name: "catalogue" , dir: "CIpipeline"}
    - {name: "user" , dir: "CIpipeline"}
    - {name: "payment" , dir: "CIpipeline"}
    - {name: "shipping" , dir: "CIpipeline"}
