
- name: included file
  ansible.builtin.include_tasks:
    file: pipeline.yml
  loop:
    - {name: "frontend" , dir: "CIpipeline"}
    - {name: "cart" , dir: "CIpipeline"}
    - {name: "catalogue" , dir: "CIpipeline"}
    - {name: "user" , dir: "CIpipeline"}
    - {name: "payment" , dir: "CIpipeline"}
    - {name: "shipping" , dir: "CIpipeline"}
