- name: Create - folder
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.7.96:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folder }}"


- name: create pipe line job
  ansible.builtin.include_tasks:
    file: pipeline.yml
  vars:
    component: "{{item.name}}"
    dir: "{{item.dir}}"
  loop: "{{ pipelinejobs }}"

