- name: Create - folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.7.96:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folder }}"


- name: create m-pipe line job
  ansible.builtin.include_tasks:
    file: m-branch-pipeline.yml
  vars:
    component: "{{item.name}}"
    dir: "{{item.dir}}"
  loop: "{{ ci_pipeline_jobs }}"

- name: create s-pipe line job
  ansible.builtin.include_tasks:
    file: s-branch-pipeline.yml
  vars:
    component: "{{item.name}}"
    dir: "{{item.dir}}"
  loop: "{{ s_ci_pipeline_jobs }}"
