
- name: Create Config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)


- name: Create - "{{dir}}/{{component}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{dir}}/{{component}}"
    url: http://172.31.7.96:8080
    user: admin
    password: "{{jenkins_password}}"