- name: Checking existing - "{{item.dir}}/{{item.name}}"
  community.general.jenkins_job_info:
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.10.175:8080
    user: admin
    password: "{{jenkins_password}}"
  register: out
  ignore_errors: yes



- name: Create Config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)
  when: out.failed | bool


- name: Create - "{{item.dir}}/{{item.name}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.10.175:8080
    user: admin
    password: "{{jenkins_password}}"
  when: out.failed | bool
