ci_pipeline_jobs:
  - { name: "frontend" , dir: "CIpipeline" }
  - { name: "cart" , dir: "CIpipeline" }
  - { name: "catalogue" , dir: "CIpipeline" }
  - { name: "user" , dir: "CIpipeline" }
  - { name: "payment" , dir: "CIpipeline" }
  - { name: "shipping" , dir: "CIpipeline" }

folder:
  - CIpipeline
  - infra
  - Contineous_Deployment

s_ci_pipeline_jobs:
  - { name: "robo-infra" , dir: "infra" }
  - { name: "roboshop-ansible" , dir: "Contineous_Deployment" }
  - { name: "roboshop-helm-chart" , dir: "Contineous_Deployment" }



